In [1]:
import pandas as pd

In [2]:
# reading csv file
df_cars = pd.read_csv('Car_sales.csv')

In [3]:
# selecting columns
df_cars = df_cars[['Manufacturer', 'Sales_in_thousands', 'Vehicle_type', 'Price_in_thousands', 'Engine_size', 'Horsepower', 'Fuel_capacity']]

In [4]:
# show dataframe
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [5]:
# calculate number of unique values
df_cars.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

##### agg()

In [9]:
# calculate the sum of columns
df_cars.agg('sum')

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [ ]:
# calculate the mean of numeric columns
# df_cars.agg('mean') # In newer versions of pandas, functions like .agg('mean') or .mean() no longer automatically ignore string columns, throwing a TypeError instead.
df_cars.mean(numeric_only=True)

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [15]:
# Different aggregations per column: calculate the sum and mean of 'Sales_in_thousands' and sum and max of 'Price_in_thousands'
df_cars.agg({'Sales_in_thousands' : ['sum', 'mean'], 'Price_in_thousands' : ['sum', 'max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [16]:
# aggregate different functions and rename the index of the resulting DataFrame.
df_cars.agg(x=('Sales_in_thousands', 'sum'), y=('Price_in_thousands', 'sum'))

   Sales_in_thousands  Price_in_thousands
x            8320.698                 NaN
y                 NaN            4245.567

##### groupby()

In [19]:
# group by Vehicle_type and calculate the mean
df_cars.groupby('Vehicle_type').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,
Car,80.622293,26.319975,3.520000,186.400000,21.895000
Passenger,43.234345,27.763200,2.902586,185.793103,16.592241

In [ ]:
# group by Manufacturer
df_cars.groupby('Manufacturer').groups.keys()

dict_keys(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mercedes-B', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo'])

In [30]:
# group by Manufacturer
groupby_obj = df_cars.groupby('Manufacturer')

In [31]:
# the groupby_obj
groupby_obj

In [32]:
# groups attribute and keys
groupby_obj.groups.keys()

dict_keys(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mercedes-B', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo'])

In [33]:
# get a specific group within the Manufacturer column
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [29]:
# get a specific group within the Manufacturer column
df_cars.groupby('Manufacturer').get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [35]:
# group by Manufacturer and calculate the mean
df_cars.groupby('Manufacturer').mean(numeric_only=True).head()

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,19.751250,30.633333,2.925000,200.000000,16.400000
Audi,13.519000,39.980000,2.933333,220.000000,19.533333
BMW,15.501667,33.096667,2.700000,185.333333,17.233333
Buick,60.504750,26.781250,3.625000,206.250000,17.750000
Cadillac,22.435600,40.254000,4.500000,256.000000,20.800000

In [37]:
# group by Manufacturer and calculate the sum
df_cars.groupby('Manufacturer').sum(numeric_only=True).head()

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,79.005,91.900,11.7,800.0,65.6
Audi,40.557,119.940,8.8,660.0,58.6
BMW,46.505,99.290,8.1,556.0,51.7
Buick,242.019,107.125,14.5,825.0,71.0
Cadillac,112.178,201.270,22.5,1280.0,104.0

In [39]:
# grou by Vehicle_type and count values
df_cars.groupby('Vehicle_type').count()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,41,41,40,40,40,40
Passenger,116,116,115,116,116,116

In [42]:
# find null values in columns
df_cars.isnull().sum()

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    2
Engine_size           1
Horsepower            1
Fuel_capacity         1
dtype: int64

In [43]:
# grou by Engine_size and count values without dropping NaN values
df_cars.groupby('Engine_size', dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0

##### Groupby() and agg()

In [45]:
# find the minimum and maximum values on each column
df_cars.groupby('Vehicle_type').agg(['min', 'max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Fuel_capacity
                       min   max
Vehicle_type
Car                   15.1  32.0
Passenger             10.3  23.7

In [46]:
# set a name for aggregated column
# find the min Engine_size and max Horsepower
df_cars.groupby('Vehicle_type').agg(min_engine_size=('Engine_size', 'min'), max_horsepower=('Horsepower', 'max'))

              min_engine_size  max_horsepower
Vehicle_type
Car                       2.0           300.0
Passenger                 1.0           450.0

In [47]:
# calculate the sum of Sales_in_thousands and mean of Price_in_thousands
df_cars.groupby('Manufacturer').agg(sum_sales=('Sales_in_thousands','sum'),mean_price=('Price_in_thousands','mean')).head()

              sum_sales  mean_price
Manufacturer
Acura            79.005   30.633333
Audi             40.557   39.980000
BMW              46.505   33.096667
Buick           242.019   26.781250
Cadillac        112.178   40.254000

In [48]:
df_cars.groupby('Manufacturer').sum()['Sales_in_thousands'].head()

Manufacturer
Acura        79.005
Audi         40.557
BMW          46.505
Buick       242.019
Cadillac    112.178
Name: Sales_in_thousands, dtype: float64

In [50]:
df_cars.groupby('Manufacturer').mean(numeric_only=True)['Price_in_thousands'].head()

Manufacturer
Acura       30.633333
Audi        39.980000
BMW         33.096667
Buick       26.781250
Cadillac    40.254000
Name: Price_in_thousands, dtype: float64