In [1]:
import pandas as pd

In [2]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [3]:
# select columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 'genre', 'country']]

df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

##### merge()

In [4]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'], 'age' : [30, 23, 25, 22]})

df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'], 'job': ['Doctor', 'Statistician' , 'Accountant', 'Developer']})

In [5]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [6]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E    Accountant
3  F     Developer

##### Inner join

In [7]:
df1.merge(df2, on='id', how='inner')

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [8]:
# shape
print(df1.shape)
print(df2.shape)
print(df1.merge(df2, on='id', how='inner').shape)

(4, 2)
(4, 2)
(2, 3)

###### Exercise

In [ ]:
# merge df_movies and df_ratings (inner join)
df_movies.merge(df_ratings, on='imdb_title_id', how='inner')
# df_movies.merge(df_ratings, on='imdb_title_id')
# pd.merge(df_movies, df_ratings, on='Imdb_title_id')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

##### Outer join (Full join)

In [12]:
df1.merge(df2, on='id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [13]:
# shape
print(df1.shape)
print(df2.shape)
print(df1.merge(df2, on='id', how='outer').shape)

(4, 2)
(4, 2)
(6, 3)

###### Exercise

In [14]:
# merge df_movies and df_ratings (outer join)
df_movies.merge(df_ratings, on='imdb_title_id', how='outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

##### Exclusive Outer join (Exclusive Full join)

In [15]:
df1.merge(df2, on='id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [17]:
# indicator=True
df1.merge(df2, on='id', how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [18]:
# query
df1.merge(df2, on='id', how='outer', indicator=True).query("_merge=='left_only' or _merge=='right_only'")

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [19]:
# shape
print(df1.shape)
print(df2.shape)
print(df1.merge(df2, on='id', how='outer', indicator=True).query("_merge=='left_only' or _merge=='right_only'").shape)

(4, 2)
(4, 2)
(4, 4)

###### Exercise

In [20]:
# merge df_movies and df_ratings
df_movies.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True).query("_merge=='left_only' or _merge=='right_only'")

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

##### Left join

In [21]:
df1.merge(df2, on='id', how='left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

###### Exercise

In [22]:
# extract a 50% sample of the df_movies dataframe
df_movies_sample = df_movies.sample(frac=0.5)

In [23]:
# merge df_movies_sample and df_ratings (left join)
df_left = df_movies_sample.merge(df_ratings, on='imdb_title_id', how='left')

In [24]:
# shape
print(df_movies_sample.shape)
print(df_ratings.shape)
print(df_left.shape)

(42928, 5)
(85855, 3)
(42928, 7)

##### Exclusive Left join

In [25]:
# indicator=True
df1.merge(df2, on='id', how='outer',
          indicator = True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [26]:
# query
df1.merge(df2, on='id', how='outer', indicator = True).query("_merge=='left_only'")

  id   age  job     _merge
0  A  30.0  NaN  left_only
1  B  23.0  NaN  left_only

In [ ]:
# left join
pd.merge(df_movies, df_ratings.sample(frac=.5), on='imdb_title_id', how='left').shape

(85855, 7)

###### Exercise

In [36]:
# make a copy of the df_movies dataframe
df_movies_2 = df_movies.copy()

In [44]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_movies_2.index:
    if index < 1000:
        df_movies_2.loc[index, 'imdb_title_id'] = 'tt1234567890'

In [45]:
# merge df_movies_2 and df_ratings (exclusive left join)
df_exclusive_left = df_movies_2.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True).query("_merge=='left_only'")

In [46]:
# shape
print(df_movies_2.shape)
print(df_ratings.shape)
print(df_exclusive_left.shape)

(85855, 6)
(85855, 3)
(1000, 9)

##### Right join

In [39]:
df1.merge(df2, on='id', how='right')

  id   age           job
0  C  25.0        Doctor
1  D  22.0  Statistician
2  E   NaN    Accountant
3  F   NaN     Developer

###### Exercise

In [41]:
# extract a 30% sample of the df_ratings dataframe
df_ratings_sample = df_ratings.sample(frac=0.3)

In [42]:
# merge df_movies and df_ratings_sample (right join)
df_right = df_movies.merge(df_ratings_sample, on='imdb_title_id', how='right')

In [43]:
# shape
print(df_movies.shape)
print(df_ratings_sample.shape)
print(df_right.shape)

(85855, 5)
(25756, 3)
(25756, 7)

##### Exclusive Right join

In [47]:
# indicator=True
df1.merge(df2, on='id', how='outer', indicator = True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [48]:
# query
df1.merge(df2, on='id', how='outer', indicator = True).query("_merge=='right_only'")

  id  age         job      _merge
4  E  NaN  Accountant  right_only
5  F  NaN   Developer  right_only

###### Exercise

In [49]:
# make a copy of the df_ratings dataframe
df_ratings_2 = df_ratings.copy()

In [50]:
# set the first 1000 values of 'imdb_title_id' column as 'tt1234567890'
for index in df_ratings_2.index:
    if index < 1000:
        df_ratings_2.loc[index, 'imdb_title_id'] = 'tt1234567890'

In [51]:
# merge df_movies and df_ratings_2 (exclusive right join)
df_exclusive_right = df_movies.merge(df_ratings_2, on='imdb_title_id', how='outer',  indicator=True).query("_merge=='right_only'")

In [52]:
# shape
print(df_movies.shape)
print(df_ratings_2.shape)
print(df_exclusive_right.shape)

(85855, 5)
(85855, 3)
(1000, 8)