In [1]:
import pandas as pd

In [38]:
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

#### Adding a new column

In [39]:
#Adding a new column with a scalar value
# adding new column to dataframe
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [2]:
import numpy as np

In [4]:
# Adding a new column with an array
# The dataframe has 1000 rows, so we need to create an array with 1000 elements
# create an array of 1000 elements
language_score = np.arange(0, 1000)

In [5]:
# Length of an array
len(language_score)

1000

In [40]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [9]:
# create random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size=1000)

In [41]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,87
1,female,group C,some college,standard,completed,69,90,88,66
2,female,group B,master's degree,standard,none,90,95,93,96
3,male,group A,associate's degree,free/reduced,none,47,57,44,32
4,male,group C,some college,standard,none,76,78,75,80
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,2
996,male,group C,high school,free/reduced,none,62,55,55,98
997,female,group C,high school,free/reduced,completed,59,71,65,67
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,39

### Add New Column with assign() and insert()

#### assign()

In [26]:
# create random numbers for our new score columns
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [27]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [42]:
# using assign() to add multiple columns
df_exams = df_exams.assign(score1=series1, score2=series2)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,87,75,98
1,female,group C,some college,standard,completed,69,90,88,66,9,65
2,female,group B,master's degree,standard,none,90,95,93,96,61,79
3,male,group A,associate's degree,free/reduced,none,47,57,44,32,73,41
4,male,group C,some college,standard,none,76,78,75,80,32,86
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,2,4,74
996,male,group C,high school,free/reduced,none,62,55,55,98,84,6
997,female,group C,high school,free/reduced,completed,59,71,65,67,98,8
998,female,group D,some college,standard,completed,68,78,77,70,43,61
999,female,group D,some college,free/reduced,none,77,86,86,39,54,60

#### insert()

In [ ]:
# using insert() to add a column at a specific position
df_exams.insert(1, 'test', series1)

In [46]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,75,group B,bachelor's degree,standard,none,72,72,74,87,75,98
1,female,9,group C,some college,standard,completed,69,90,88,66,9,65
2,female,61,group B,master's degree,standard,none,90,95,93,96,61,79
3,male,73,group A,associate's degree,free/reduced,none,47,57,44,32,73,41
4,male,32,group C,some college,standard,none,76,78,75,80,32,86
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,4,group E,master's degree,standard,completed,88,99,95,2,4,74
996,male,84,group C,high school,free/reduced,none,62,55,55,98,84,6
997,female,98,group C,high school,free/reduced,completed,59,71,65,67,98,8
998,female,43,group D,some college,standard,completed,68,78,77,70,43,61
999,female,54,group D,some college,free/reduced,none,77,86,86,39,54,60