In [1]:
import pandas as pd

In [ ]:
# reading and showing dataframe
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

##### Create Index

In [3]:
import numpy as np
import random

In [4]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [5]:
# shuffling the indexes
random.shuffle(new_index)
new_index

array([946, 464, 323, 142, 674, 244, 129, 266, 530, 136, 998, 503, 919,
       456, 921,  23, 313, 196, 711, 541, 968, 696, 796, 770, 180, 793,
       738, 733, 959, 966, 112, 121, 349, 826, 931, 420, 434,  85,  87,
       743, 971, 773, 122, 108, 501, 154,   0, 656, 426, 103, 438, 651,
       989,  54, 575, 382, 335, 293, 114, 547,  31, 927, 691, 598, 329,
       948, 415, 544, 141,  15, 462, 701, 279, 703, 844, 411, 552, 298,
       700, 926, 909, 945, 240, 348, 336, 882, 171, 133, 637, 960,  67,
       327, 950, 818,  70, 835, 874, 592, 502, 423, 506, 120, 294, 585,
       118, 607, 268, 695,  73, 720, 962, 248, 181, 847, 811, 721, 713,
       487, 915, 523,  89,  49, 976, 856, 381, 505, 917, 779, 459,  40,
       914, 888, 406, 351, 589, 596, 877, 850, 224, 671, 839, 808, 101,
       910,  79, 222, 290,  80, 612, 908, 467, 463, 574, 139, 994, 202,
       588, 706, 819, 179, 768, 383, 399, 809, 378, 413, 246, 215, 967,
       303, 504, 887, 545, 663, 439, 984, 212, 163, 265, 205, 755, 595,
       297, 241, 448, 317, 391, 479, 521,  32, 412, 366, 119, 332, 249,
       218, 694, 394, 419,  64,   6, 470, 187, 227, 288, 924, 734, 586,
        59, 257, 316, 157, 387, 328, 211, 261, 304,  33, 350, 405, 183,
       104, 843, 418,  97, 631, 310, 245, 375, 409, 449, 982, 535, 522,
       578, 563, 964, 609, 756, 814, 158, 345, 296, 175, 289, 161, 716,
       881, 763, 615, 468, 311, 274, 821, 963, 759, 302, 767, 889, 494,
       838, 422, 937, 869, 704,  12,   8, 974, 897, 362, 655,   3, 455,
       623, 283, 636, 904, 278, 356, 216, 461, 820, 697, 559, 486, 951,
        75, 176,   2, 997, 993, 508, 186, 570, 977, 634, 197, 729, 243,
       469, 676, 390, 624,  99, 159, 605, 258, 972, 965, 583, 958, 513,
       970, 648, 368, 194, 191, 907, 489, 172, 786, 639, 259, 593, 795,
        13, 315, 567, 165, 482, 145,  42, 935, 824, 255,  91, 558, 599,
       164, 569, 709, 483, 518, 668, 428, 961, 730, 749, 831, 206, 801,
       340, 724, 858, 956, 389, 305,  46, 476, 480, 789, 933, 111, 580,
        58,  82, 833, 325, 536, 621, 834, 787, 267, 805, 871, 231, 437,
        22, 498, 346, 373, 785, 237,  43, 107, 162, 230, 594, 520, 896,
        27, 550, 128, 416, 436, 286, 600, 865, 890, 799, 606, 301, 424,
       643, 254, 608, 471, 339, 272,   7, 363, 727, 611, 912, 723, 870,
       182, 954, 629, 616, 778, 285, 747, 622, 430, 708, 782, 684, 902,
       287, 751, 184, 693, 560, 601, 837, 677, 277, 642,  65, 760, 930,
       192, 208, 995, 683, 147, 210, 780, 566, 863, 372, 115, 214, 233,
       992, 630, 410, 939, 239, 546, 178,  81, 242,  38, 564, 220, 650,
       735, 988, 617, 232, 579, 140, 250, 604, 537, 670, 667, 790, 657,
       991, 810, 106, 403,  10, 131, 936, 170, 511, 804, 370, 130, 752,
       794, 764, 753, 800, 687, 396,  26,   9,  90, 167, 886,  74, 453,
       551, 854, 736,  63, 529, 515, 442, 260,  17, 514, 324, 174,  71,
       384, 849, 928, 492, 942, 555, 660, 478,  68, 816, 397,  19, 331,
       132, 807, 319, 784,  83, 353, 369, 774, 527, 880, 732, 698, 688,
       314, 519, 393,  16, 374, 679, 851, 762, 645, 156, 454, 918, 275,
       925,  86, 238, 952, 672, 226, 431, 728, 556, 852, 842, 474, 117,
       534, 714, 355, 500, 848, 223, 445, 320, 235,  77, 885, 603, 347,
       632, 572, 251,  96,  69, 152, 173, 549, 292, 203, 102, 640, 792,
       771, 652, 827, 507, 444,  93, 975, 990, 127, 879,  84, 150, 247,
       875, 427, 944, 517, 573, 571,  34,  36, 554, 941, 440, 983, 198,
       146, 307, 330, 682, 195, 702, 429, 627, 661,  25, 291, 371, 388,
       635, 690, 987, 719, 644, 280, 308, 969, 276, 151, 400, 516, 803,
       828,  28, 741, 435, 710, 553, 496, 395, 748,  57, 853, 333, 726,
       344, 110, 857, 357, 354,  62,  41, 543, 509, 610,  24, 932, 284,
       488, 125, 201, 934, 802, 985, 669, 148, 955, 105, 766, 458, 100,
       797, 620, 264, 873, 269, 817, 134, 922, 510, 300, 166, 562, 699,
       169, 499, 137, 587, 484, 123,  50, 126, 539, 576, 177, 894, 878,
       495, 367, 649, 189, 538, 213, 722, 234, 653, 832, 221, 876, 185,
       452, 365, 417, 524, 466, 581, 135, 358, 830, 160, 318, 360, 980,
       916, 846, 905, 662, 457, 957, 841, 757, 861, 256, 626,  51, 446,
       168, 618, 309, 217, 193, 407, 798, 680, 633, 273, 116, 531, 337,
       225, 404, 772, 312, 512, 352, 590, 900, 219, 200,  94, 568, 386,
       788, 860, 754, 190, 825, 425, 364, 665, 659, 270, 252, 361, 906,
       421, 380, 149, 532, 981, 868, 783, 823, 441, 490,  92, 973, 938,
       678, 625, 666, 262, 943, 658, 109, 675, 692,  60,  37, 822, 866,
       628, 883, 432, 542, 895, 829, 475, 947, 740, 840, 402,  55, 433,
       584, 299, 493,  29, 155, 717, 731, 654, 591, 613,  98, 341, 725,
        95, 681, 899, 597, 229, 392, 377, 705,  52, 750,  45, 548, 143,
       414, 460, 207, 472, 845, 447, 765, 614,   4, 744, 497, 898, 582,
       920, 893, 485, 758,  14, 401, 777, 806, 408, 746, 999,  11, 986,
       376, 359, 911, 338, 326, 144, 859, 903,  20, 689, 815, 465, 739,
       712,  61, 477, 664, 271, 204, 321, 647, 334,  78, 638, 577,  35,
       836, 306, 949, 557,   1,  88,  30, 561, 263, 188, 953,  76, 996,
       398,  72, 295, 742, 540, 872, 450, 253, 602, 282, 855, 641, 715,
       707, 199, 901, 281, 673,  48,  39,  53, 481, 343, 533, 761, 646,
       737, 978,   5, 745, 884,  21, 929, 153, 342,  56, 862, 209, 525,
       379,  66, 775, 491, 718, 443, 685, 565, 619, 473, 923, 385, 891,
       686, 138, 812, 892, 124, 526, 781, 113, 979, 940, 791,  18,  44,
       776, 813, 322,  47, 228, 864, 867, 451, 236, 769, 913, 528])

In [6]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,946
1,female,group C,some college,standard,completed,69,90,88,464
2,female,group B,master's degree,standard,none,90,95,93,323
3,male,group A,associate's degree,free/reduced,none,47,57,44,142
4,male,group C,some college,standard,none,76,78,75,674
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,451
996,male,group C,high school,free/reduced,none,62,55,55,236
997,female,group C,high school,free/reduced,completed,59,71,65,769
998,female,group D,some college,standard,completed,68,78,77,913
999,female,group D,some college,free/reduced,none,77,86,86,528

##### Set Index

In [7]:
# set new_index column as index
df_exams.set_index('new_index', inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
946,female,group B,bachelor's degree,standard,none,72,72,74
464,female,group C,some college,standard,completed,69,90,88
323,female,group B,master's degree,standard,none,90,95,93
142,male,group A,associate's degree,free/reduced,none,47,57,44
674,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
451,female,group E,master's degree,standard,completed,88,99,95
236,male,group C,high school,free/reduced,none,62,55,55
769,female,group C,high school,free/reduced,completed,59,71,65
913,female,group D,some college,standard,completed,68,78,77
528,female,group D,some college,free/reduced,none,77,86,86

##### Sort Index

In [8]:
# sort dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,female,group A,associate's degree,standard,completed,55,65,62
1,female,group B,associate's degree,free/reduced,none,46,61,55
2,male,group B,bachelor's degree,free/reduced,none,88,75,76
3,male,group C,some college,standard,none,58,49,42
4,male,group C,high school,free/reduced,none,59,53,52
...,...,...,...,...,...,...,...,...
995,male,group A,some high school,free/reduced,none,79,82,73
996,male,group D,high school,standard,none,72,66,66
997,male,group E,some high school,standard,completed,77,76,77
998,male,group C,associate's degree,standard,none,58,54,52
999,female,group E,bachelor's degree,standard,completed,71,70,70

In [9]:
# sort descending by index
df_exams.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group E,bachelor's degree,standard,completed,71,70,70
998,male,group C,associate's degree,standard,none,58,54,52
997,male,group E,some high school,standard,completed,77,76,77
996,male,group D,high school,standard,none,72,66,66
995,male,group A,some high school,free/reduced,none,79,82,73
...,...,...,...,...,...,...,...,...
4,male,group C,high school,free/reduced,none,59,53,52
3,male,group C,some college,standard,none,58,49,42
2,male,group B,bachelor's degree,free/reduced,none,88,75,76
1,female,group B,associate's degree,free/reduced,none,46,61,55
0,female,group A,associate's degree,standard,completed,55,65,62